import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "./components/header/Header";
import "./globals.css";

const Montserrat = localFont({
  src: [
    {
      path: "./fonts/Montserrat-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Montserrat-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Montserrat-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Montserrat-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${Montserrat.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
